name: Cinema CI/CD pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - infrastructure/**

jobs:

  build-the-docker-image:

    runs-on: ubuntu-latest

    steps:
      - name: Check the Repository
        uses: actions/checkout@v4

      - name: Log in to the aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to the AWS ECR registry
        uses: aws-actions/amazon-ecr-login@v2

      - name: Add Version Tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build the Catalog Docker Image and Push it into ECR
        run: |
          docker build -t ${{ secrets.CATALOG_SERVICE_REPO}}:$IMAGE_TAG ./services/catalog-service
          docker push ${{ secrets.CATALOG_SERVICE_REPO}}:$IMAGE_TAG

      - name: Build the User service Docker Image and Push it into ECR
        run: |
          docker build -t ${{ secrets.USER_SERVICE_REPO}}:$IMAGE_TAG ./services/user-service
          docker push ${{ secrets.USER_SERVICE_REPO}}:$IMAGE_TAG


      - name: Build the Gateway Docker Image and Push it into ECR
        run: |
          docker build -t ${{ secrets.GATEWAY_REPO}}:$IMAGE_TAG ./services/gateway
          docker push ${{ secrets.GATEWAY_REPO}}:$IMAGE_TAG

      - name: Build the Frontend Docker Image and Push it into ECR
        run: |
          docker build -t ${{ secrets.FRONT_END_REPO}}:$IMAGE_TAG ./frontend
          docker push ${{ secrets.FRONT_END_REPO}}:$IMAGE_TAG






# --------------      Catalog Section     --------------

      - name: Download current catalog task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition Cinema-catalog \
            --query taskDefinition > catalog-task-def.json

      - name: Clean the Catalog Task Definition JSON files
        run: |
          jq '
            del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            )
          ' catalog-task-def.json > clean-catalog-task-def.json

      
      - name: Render new catalog task definition (inject new image)
        run: |
          jq --arg IMAGE "${{ secrets.CATALOG_SERVICE_REPO}}:$IMAGE_TAG" \
          '.containerDefinitions[0].image = $IMAGE' clean-catalog-task-def.json > new-catalog-task-def.json


      - name: Register new catalog task definition revision
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-catalog-task-def.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
          echo "Registered new Catalog task definition: $TASK_DEF_ARN"

      - name: Update ECS catalog service
        run: |
          aws ecs update-service \
            --cluster Cinema-Cluster \
            --service Cinema-catalog-service \
            --task-definition $TASK_DEF_ARN \
            --force-new-deployment          






# --------------      User-Service Section       --------------

      - name: Download current user-service task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition Cinema-user-service \
            --query taskDefinition > user-service-task-def.json

      - name: Clean the Task Definition JSON files
        run: |
          jq '
            del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            )
          ' user-service-task-def.json > clean-user-service-task-def.json

      
      - name: Render new user-service task definition (inject new image)
        run: |
          jq --arg IMAGE "${{ secrets.USER_SERVICE_REPO}}:$IMAGE_TAG" \
          '.containerDefinitions[0].image = $IMAGE' clean-user-service-task-def.json > new-user-service-task-def.json


      - name: Register new user-service task definition revision
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-user-service-task-def.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
          echo "Registered new User Service task definition: $TASK_DEF_ARN"

      - name: Update ECS user-sevice service
        run: |
          aws ecs update-service \
            --cluster Cinema-Cluster \
            --service Cinema-user-service \
            --task-definition $TASK_DEF_ARN \
            --force-new-deployment 






# --------------      Gateway Section        --------------

      - name: Download current gateway task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition Cinema-gateway \
            --query taskDefinition > gateway-task-def.json

      - name: Clean the Task Definition JSON files
        run: |
          jq '
            del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            )
          ' gateway-task-def.json > clean-gateway-task-def.json

      
      - name: Render new gateway task definition (inject new image)
        run: |
          jq --arg IMAGE "${{ secrets.GATEWAY_REPO}}:$IMAGE_TAG" \
          '.containerDefinitions[0].image = $IMAGE' clean-gateway-task-def.json > new-gateway-task-def.json


      - name: Register new gateway task definition revision
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-gateway-task-def.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
          echo "Registered new Gateway task definition: $TASK_DEF_ARN"


      - name: Update ECS gateway service
        run: |
          aws ecs update-service \
            --cluster Cinema-Cluster \
            --service Cinema-gateway-service \
            --task-definition $TASK_DEF_ARN \
            --force-new-deployment









# --------------      Frontend Section          --------------

      - name: Download current frontendtask definition
        run: |
          aws ecs describe-task-definition \
            --task-definition Cinema-frontend \
            --query taskDefinition > frontend-task-def.json

      - name: Clean the Task Definition JSON files
        run: |
          jq '
            del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            )
          ' frontend-task-def.json > clean-frontend-task-def.json

      
      - name: Render new frontend task definition (inject new image)
        run: |
          jq --arg IMAGE "${{ secrets.FRONT_END_REPO}}:$IMAGE_TAG" \
          '.containerDefinitions[0].image = $IMAGE' clean-frontend-task-def.json > new-frontend-task-def.json


      - name: Register new frontend task definition revision
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-frontend-task-def.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
          echo "Registered new Frontend task definition: $TASK_DEF_ARN"

      - name: Update ECS frontend service
        run: |
          aws ecs update-service \
            --cluster Cinema-Cluster \
            --service Cinema-frontend-service \
            --task-definition $TASK_DEF_ARN \
            --force-new-deployment


      

      
      
      
      
      
      
      
      
      
      
      
      











#      - name: Wait for service stability
#        run: |
#          aws ecs wait services-stable \
#            --cluster Cinema-Cluster \
#            --services \
#              Cinema-catalog-service \
#              Cinema-user-service \
#              Cinema-frontend-service \
#              Cinema-gateway-service
