name: Cinema CI/CD pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - infrastructure/**

jobs:

  build-the-docker-image:

    runs-on: ubuntu-latest

    steps:
      - name: Check the Repository
        uses: actions/checkout@v4

      - name: Log in to the aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to the AWS ECR registry
        uses: aws-actions/amazon-ecr-login@v2

      - name: Add Version Tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build the Frontend Docker Image and Push it into ECR
        run: |
          docker pull nginx:latest
          docker tag nginx:latest ${{ secrets.FRONT_END_REPO}}:$IMAGE_TAG
          docker push ${{ secrets.FRONT_END_REPO}}:$IMAGE_TAG

# docker build -t ${{ secrets.FRONT_END_REPO}}:$IMAGE_TAG 

      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition Cinema-frontend \
            --query taskDefinition > frontend-task-def.json

      - name: Clean the Task Definition JSON files
        run: |
          jq '
            del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            )
          ' frontend-task-def.json > clean-frontend-task-def.json

      
      - name: Render new task definition (inject new image)
        run: |
          jq --arg IMAGE "${{ secrets.FRONT_END_REPO}}:$IMAGE_TAG" \
          '.containerDefinitions[0].image = $IMAGE' clean-frontend-task-def.json > new-frontend-task-def.json


      - name: Register new task definition revision
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-frontend-task-def.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
          echo "Registered new task definition: $TASK_DEF_ARN"

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster Cinema-Cluster \
            --service Cinema-frontend-service \
            --task-definition $TASK_DEF_ARN \
            --force-new-deployment

      - name: Wait for service stability
        run: |
          aws ecs wait services-stable \
            --cluster Cinema-Cluster \
            --services Cinema-frontend-service