name: Cinema CI/CD pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - infrastructure/**

jobs:

  build-the-docker-image:

    runs-on: ubuntu-latest

    steps:
      - name: Check the Repository
        uses: actions/checkout@v4

      - name: Log in to the aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to the AWS ECR registry
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Add Version Tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build the Frontend Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          FRONT_END_REPO: ${{ secrets.FRONT_END_REPO }}
        run: |
          ECR_REPOSITORY="${FRONT_END_REPO#*/}"
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY"
          docker build -t "$IMAGE_URI:$IMAGE_TAG" ./frontend
          docker push "$IMAGE_URI:$IMAGE_TAG"