name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-the-docker-image:

    runs-on: ubuntu-latest

    steps:
      - name: Check the Repository
        uses: actions/checkout@v4

      - name: Log in to the DockerHub registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build the catalog-service image
        run: docker build ./services/catalog-services --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/movie-streamer-catalog-services:latest

      - name: Build the gateway image
        run: docker build ./services/gateway --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/movie-streamer-gateway:latest

      - name: Build the user-service image
        run: docker build ./services/user-service --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/movie-streamer-user-service:latest

      - name: Build the frontend image
        run: docker build ./frontend --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/movie-streamer-frontend:latest

      - name: Push the catalog-service image into Registry
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/movie-streamer-catalog-services:latest

      - name: Push the gateway image into Registry
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/movie-streamer-catalog-services:latest

      - name: Push the user-service image into Registry
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/movie-streamer-user-service:latest

      - name: Push the frontend image into Registry
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/movie-streamer-frontend:latest
